name: Release Windows (Bun + Tauri)

on:
  push:
    tags:
      - "v*.*.*"   # v1.0.0 のようなタグで実行

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      # Rust (Tauri のバックエンド)
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # Bun (フロントエンド)
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # 依存関係インストール
      - name: Install dependencies
        run: bun install

      # Tauri ビルド
      - name: Build Tauri App
        run: bun run tauri build

      # GitHub Release にアップロード
      - name: Upload to Release
        uses: tauri-apps/tauri-action@v0
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "Release ${{ github.ref_name }}"
          releaseBody: "Windows installer and updater manifest"
          releaseDraft: false
          prerelease: false
